name: build-publish-docker-image

on: 
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.travis.yml'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      LATEX_IMAGE_TAG: "3.1"
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Bash Automated Testing System (BATS)
        run: npm install -g bats

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: rstropek/pandoc-latex:test
          build-args: 'LATEX_IMAGE_TAG=${{ env.LATEX_IMAGE_TAG }}'

      - name: Run BATS Tests
        run: bats tests/test-example-generation.bats

      - name: Docker Tags
        run: |
          docker tag rstropek/pandoc-latex:test rstropek/pandoc-latex:${{ env.LATEX_IMAGE_TAG }} 
          docker tag rstropek/pandoc-latex:test rstropek/pandoc-latex:latest
        
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rstropek/pandoc-latex:${{ env.LATEX_IMAGE_TAG }}
          build-args: 'LATEX_IMAGE_TAG=${{ env.LATEX_IMAGE_TAG }}'
        
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rstropek/pandoc-latex:latest
          build-args: 'LATEX_IMAGE_TAG=${{ env.LATEX_IMAGE_TAG }}'
